# **Install Libraries**

In [1]:
pip install pyspark

Collecting pyspark
  Downloading pyspark-3.5.0.tar.gz (316.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.9/316.9 MB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.0-py2.py3-none-any.whl size=317425345 sha256=6373e6a5ac15ea6a97df0caa6af68a4d28068450074c20979b253a00f6ddfbd8
  Stored in directory: /root/.cache/pip/wheels/41/4e/10/c2cf2467f71c678cfc8a6b9ac9241e5e44a01940da8fbb17fc
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.0

In [2]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q http://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz
!tar xf spark-3.1.1-bin-hadoop3.2.tgz
!pip install -q findspark
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.1-bin-hadoop3.2"

In [3]:
import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()
from pyspark.sql.functions import *
import pyspark.sql.functions as sqlfunc

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **Import Data**

In [5]:
df = spark.read.format("csv").option("header","true").load("/content/drive/MyDrive/pyspark_crachcourse/original.csv")
df.show(6)

+---+----------+----------+------+---------------+--------------------+---------+----------+-----------+
| id|first_name| last_name|gender|           City|            JobTitle|   Salary|  Latitude|  Longitude|
+---+----------+----------+------+---------------+--------------------+---------+----------+-----------+
|  1|   Melinde| Shilburne|Female|      Nowa Ruda| Assistant Professor|$57438.18|50.5774075| 16.4967184|
|  2|  Kimberly|Von Welden|Female|         Bulgan|       Programmer II|$62846.60|48.8231572|103.5218199|
|  3|    Alvera|  Di Boldi|Female|           null|                null|$57576.52|39.9947462|116.3397725|
|  4|   Shannon| O'Griffin|  Male|  Divnomorskoye|Budget/Accounting...|$61489.23|44.5047212| 38.1300171|
|  5|  Sherwood|   Macieja|  Male|      Mytishchi|            VP Sales|$63863.09|      null| 37.6489954|
|  6|     Maris|      Folk|Female|Kinsealy-Drinan|      Civil Engineer|$30101.16|53.4266145| -6.1644997|
+---+----------+----------+------+---------------+--------------------+---------+----------+-----------+
only showing top 6 rows

In [6]:
# To get DataFrame Data Types
df.dtypes

[('id', 'string'),
 ('first_name', 'string'),
 ('last_name', 'string'),
 ('gender', 'string'),
 ('City', 'string'),
 ('JobTitle', 'string'),
 ('Salary', 'string'),
 ('Latitude', 'string'),
 ('Longitude', 'string')]

In [7]:
# Create Schema that have specific Data Types
from pyspark.sql.types import *

myschema = StructType([
    StructField("id", IntegerType(), True),
    StructField("first_name",StringType(),True),
    StructField("last_name",StringType(),True),
    StructField("gender",StringType(),True),
    StructField("City",StringType(),True),
    StructField("JobTitle",StringType(),True),
    StructField("Salary",StringType(),True),
    StructField("Latitude",FloatType(),True),
    StructField("Longitude",FloatType(),True)
])

In [8]:
df1 = spark.read.csv("/content/drive/MyDrive/pyspark_crachcourse/original.csv", header = True, schema=myschema)
df1.show(6)

+---+----------+----------+------+---------------+--------------------+---------+---------+----------+
| id|first_name| last_name|gender|           City|            JobTitle|   Salary| Latitude| Longitude|
+---+----------+----------+------+---------------+--------------------+---------+---------+----------+
|  1|   Melinde| Shilburne|Female|      Nowa Ruda| Assistant Professor|$57438.18|50.577408| 16.496717|
|  2|  Kimberly|Von Welden|Female|         Bulgan|       Programmer II|$62846.60| 48.82316| 103.52182|
|  3|    Alvera|  Di Boldi|Female|           null|                null|$57576.52|39.994747|116.339775|
|  4|   Shannon| O'Griffin|  Male|  Divnomorskoye|Budget/Accounting...|$61489.23|44.504723| 38.130016|
|  5|  Sherwood|   Macieja|  Male|      Mytishchi|            VP Sales|$63863.09|     null| 37.648994|
|  6|     Maris|      Folk|Female|Kinsealy-Drinan|      Civil Engineer|$30101.16|53.426613|-6.1644998|
+---+----------+----------+------+---------------+--------------------+---------+---------+----------+
only showing top 6 rows

# **Data Manipulation**

In [9]:
df1.dtypes

[('id', 'int'),
 ('first_name', 'string'),
 ('last_name', 'string'),
 ('gender', 'string'),
 ('City', 'string'),
 ('JobTitle', 'string'),
 ('Salary', 'string'),
 ('Latitude', 'float'),
 ('Longitude', 'float')]

In [10]:
df1.head(6)

[Row(id=1, first_name='Melinde', last_name='Shilburne', gender='Female', City='Nowa Ruda', JobTitle='Assistant Professor', Salary='$57438.18', Latitude=50.57740783691406, Longitude=16.49671745300293),
 Row(id=2, first_name='Kimberly', last_name='Von Welden', gender='Female', City='Bulgan', JobTitle='Programmer II', Salary='$62846.60', Latitude=48.823158264160156, Longitude=103.52182006835938),
 Row(id=3, first_name='Alvera', last_name='Di Boldi', gender='Female', City=None, JobTitle=None, Salary='$57576.52', Latitude=39.994747161865234, Longitude=116.33977508544922),
 Row(id=4, first_name='Shannon', last_name="O'Griffin", gender='Male', City='Divnomorskoye', JobTitle='Budget/Accounting Analyst II', Salary='$61489.23', Latitude=44.504722595214844, Longitude=38.1300163269043),
 Row(id=5, first_name='Sherwood', last_name='Macieja', gender='Male', City='Mytishchi', JobTitle='VP Sales', Salary='$63863.09', Latitude=None, Longitude=37.64899444580078),
 Row(id=6, first_name='Maris', last_name='Folk', gender='Female', City='Kinsealy-Drinan', JobTitle='Civil Engineer', Salary='$30101.16', Latitude=53.426612854003906, Longitude=-6.164499759674072)]

In [11]:
df1.first()

Row(id=1, first_name='Melinde', last_name='Shilburne', gender='Female', City='Nowa Ruda', JobTitle='Assistant Professor', Salary='$57438.18', Latitude=50.57740783691406, Longitude=16.49671745300293)

In [12]:
df1.describe().show()

+-------+-----------------+----------+---------+------+-------------------+-------------------+---------+------------------+-----------------+
|summary|               id|first_name|last_name|gender|               City|           JobTitle|   Salary|          Latitude|        Longitude|
+-------+-----------------+----------+---------+------+-------------------+-------------------+---------+------------------+-----------------+
|  count|             1000|      1000|     1000|  1000|                999|                998|     1000|               999|             1000|
|   mean|            500.5|      null|     null|  null|               null|               null|     null| 25.43151724702484|43.33756460386515|
| stddev|288.8194360957494|      null|     null|  null|               null|               null|     null|24.579082550156635| 69.4206453674681|
|    min|                1|   Abagail|    Abbay|Female|             Abéché|Account Coordinator|$10101.92|         -54.28115|       -123.04196|
|    max|             1000|    Zulema| de Marco|  Male|‘Aşīrah al Qiblīyah|   Web Developer IV|$99948.28|          69.63186|        175.28227|
+-------+-----------------+----------+---------+------+-------------------+-------------------+---------+------------------+-----------------+

In [13]:
df1.columns

['id',
 'first_name',
 'last_name',
 'gender',
 'City',
 'JobTitle',
 'Salary',
 'Latitude',
 'Longitude']

In [14]:
df1.count()

1000

In [15]:
df1.distinct().count()

1000

#**Handling Null and Duplicated Values**

In [16]:
df_dropped = df1.na.drop()
df_dropped.show(4)

+---+----------+----------+------+---------------+--------------------+---------+---------+----------+
| id|first_name| last_name|gender|           City|            JobTitle|   Salary| Latitude| Longitude|
+---+----------+----------+------+---------------+--------------------+---------+---------+----------+
|  1|   Melinde| Shilburne|Female|      Nowa Ruda| Assistant Professor|$57438.18|50.577408| 16.496717|
|  2|  Kimberly|Von Welden|Female|         Bulgan|       Programmer II|$62846.60| 48.82316| 103.52182|
|  4|   Shannon| O'Griffin|  Male|  Divnomorskoye|Budget/Accounting...|$61489.23|44.504723| 38.130016|
|  6|     Maris|      Folk|Female|Kinsealy-Drinan|      Civil Engineer|$30101.16|53.426613|-6.1644998|
+---+----------+----------+------+---------------+--------------------+---------+---------+----------+
only showing top 4 rows

In [17]:
df_null_jobs = df1.filter(
    df1.JobTitle.isNotNull()
)
df_null_jobs.show(4)

+---+----------+----------+------+-------------+--------------------+---------+---------+---------+
| id|first_name| last_name|gender|         City|            JobTitle|   Salary| Latitude|Longitude|
+---+----------+----------+------+-------------+--------------------+---------+---------+---------+
|  1|   Melinde| Shilburne|Female|    Nowa Ruda| Assistant Professor|$57438.18|50.577408|16.496717|
|  2|  Kimberly|Von Welden|Female|       Bulgan|       Programmer II|$62846.60| 48.82316|103.52182|
|  4|   Shannon| O'Griffin|  Male|Divnomorskoye|Budget/Accounting...|$61489.23|44.504723|38.130016|
|  5|  Sherwood|   Macieja|  Male|    Mytishchi|            VP Sales|$63863.09|     null|37.648994|
+---+----------+----------+------+-------------+--------------------+---------+---------+---------+
only showing top 4 rows

In [18]:
df_no_dupli = df1.dropDuplicates()
df_no_dupli.show(4)

+---+----------+---------+------+----------+--------------------+---------+----------+---------+
| id|first_name|last_name|gender|      City|            JobTitle|   Salary|  Latitude|Longitude|
+---+----------+---------+------+----------+--------------------+---------+----------+---------+
|372|     Lyman|  Burfitt|  Male|   Guiping|Community Outreac...|$28755.53| 23.394325|110.07938|
|391|     Verge| Hefferan|  Male|Cocachacra|Community Outreac...|$90391.71|-17.091843|-71.77114|
|428|   Pernell|  Fossitt|  Male| Wangchang|    Graphic Designer|$36927.53| 40.401047| 117.9989|
|526|  Garfield|Benadette|  Male|    Shiren|   Marketing Manager|$56867.78| 28.651703|117.90413|
+---+----------+---------+------+----------+--------------------+---------+----------+---------+
only showing top 4 rows

In [19]:
df_no_dupli.count()

1000

#**Selecting and Filtering Data**

In [20]:
df_full_name = df1.select(
    "first_name",
    "last_name"
)
df_full_name.show(2)

+----------+----------+
|first_name| last_name|
+----------+----------+
|   Melinde| Shilburne|
|  Kimberly|Von Welden|
+----------+----------+
only showing top 2 rows

In [21]:
df_full_name = df_full_name.withColumnRenamed("first_name", "fn").withColumnRenamed("last_name", "ln")

df_full_name.show(2)

+--------+----------+
|      fn|        ln|
+--------+----------+
| Melinde| Shilburne|
|Kimberly|Von Welden|
+--------+----------+
only showing top 2 rows

In [22]:
df1.filter(
    (df1.first_name == 'Maris')
).show()

+---+----------+---------+------+---------------+--------------+---------+---------+----------+
| id|first_name|last_name|gender|           City|      JobTitle|   Salary| Latitude| Longitude|
+---+----------+---------+------+---------------+--------------+---------+---------+----------+
|  6|     Maris|     Folk|Female|Kinsealy-Drinan|Civil Engineer|$30101.16|53.426613|-6.1644998|
+---+----------+---------+------+---------------+--------------+---------+---------+----------+

In [23]:
df1.filter(
    (df1.JobTitle.endswith("Engineer"))
).show()

+---+----------+-----------+------+--------------------+--------------------+---------+----------+----------+
| id|first_name|  last_name|gender|                City|            JobTitle|   Salary|  Latitude| Longitude|
+---+----------+-----------+------+--------------------+--------------------+---------+----------+----------+
|  6|     Maris|       Folk|Female|     Kinsealy-Drinan|      Civil Engineer|$30101.16| 53.426613|-6.1644998|
| 10|      Bran|    Trahear|  Male|            Arbeláez|Mechanical System...|$68098.42|  4.272793|-74.416016|
| 11|    Kylynn|    Lockart|Female|            El Cardo|Nuclear Power Eng...|$13604.63|     -5.85| -79.88333|
| 18|     Thain|     Habbon|  Male|      Foros do Trapo|     Design Engineer|$42135.67| 38.696247| -8.709834|
| 30|    Cherey|      Liger|Female|               Itami|     Design Engineer|$94566.69|  34.77912|  135.4204|
| 33|     Odell|    Morritt|  Male|Chalan Pago-Ordot...|     Design Engineer|$72777.48| 13.444138| 144.78209|
| 46|    Sollie|     D'Acth|  Male|              Mozdok|     Design Engineer|$31385.87|  43.74542| 44.683067|
| 48|    Farlee|     Callen|  Male|         Tanjungluar|Structural Analys...|$16866.41| -8.776544| 116.50937|
| 51|      Devi| Brownsmith|Female|      Mariano Moreno|Structural Analys...|$11376.58| -34.70618|-58.312477|
| 62|  Pierette|    Zanelli|Female|          Chōfugaoka|Senior Quality En...|$72918.12| 35.655346| 139.54764|
| 84|      Dael|     Bediss|  Male|   Chaloem Phra Kiat|      Civil Engineer|$54840.20| 9.9533825|  98.61117|
| 89|     Pablo|    Whytock|  Male|Villa Paula de Sa...|Mechanical System...|$94648.51|-32.884205|-68.799805|
| 96|   Colette|Corradeschi|Female|           Piekoszów| Geological Engineer|$78229.00| 50.881638| 20.465929|
| 99| Margarete|Andreopolos|Female|           Neglasari|    Quality Engineer|$23216.03| -6.147133| 106.62324|
|103|Westbrooke| Itchingham|  Male|          Đông Thành|Structural Analys...|$23180.71| 20.263956| 105.97534|
|108|    Miriam|      Jertz|Female|               Hekou|    Quality Engineer|$27902.32| 22.529404| 103.93935|
|136|    Kellby|  Hamprecht|  Male|         Horodyshche|Chief Design Engi...|$23203.43| 49.291775| 31.446533|
|141|   Klement|Meadowcroft|  Male|            Fāraskūr|Structural Analys...|$16800.32| 31.329103| 31.713299|
|148|    Lizzie|    Cridlin|Female|            Kenamoen| Electrical Engineer|$69631.29|  -10.5411|  123.2875|
|176|    Gustaf| Warrington|  Male|              Imbang|    Product Engineer|$46385.22| 11.099042| 122.65339|
+---+----------+-----------+------+--------------------+--------------------+---------+----------+----------+
only showing top 20 rows

In [24]:
df1.filter(
    (df1.JobTitle.startswith("Computer"))
).show()

+---+----------+---------+------+--------+--------------------+---------+---------+---------+
| id|first_name|last_name|gender|    City|            JobTitle|   Salary| Latitude|Longitude|
+---+----------+---------+------+--------+--------------------+---------+---------+---------+
|279|    Walliw|   Rotham|Female| Mattawa|Computer Systems ...|$87553.73| 46.31681|-78.69957|
|524|    Ofilia| Gilhespy|Female|Tiandiba|Computer Systems ...|$11950.08|28.721764|108.38986|
|624|    Esdras| Trangmar|  Male| Islamey|Computer Systems ...|$93275.42|43.686535|43.519264|
+---+----------+---------+------+--------+--------------------+---------+---------+---------+

In [25]:
df1.filter(
    (df1.JobTitle.like("Data%"))
).show()

+---+----------+-----------+------+-----------------+--------------------+---------+----------+----------+
| id|first_name|  last_name|gender|             City|            JobTitle|   Salary|  Latitude| Longitude|
+---+----------+-----------+------+-----------------+--------------------+---------+----------+----------+
| 44|   Orville|  Rigardeau|  Male|          Kokotów|     Data Coordiator|$20350.35| 50.014263| 20.096687|
|248|     Lefty|      Osler|  Male|          Warmare|     Data Coordiator|$90661.46| -0.970213|  133.9246|
|302|     Adams|     Hempel|  Male|           Godong|     Data Coordiator|$39141.71|-7.0519443| 110.74801|
|332|    Freddy|Rosenwasser|Female|          Shar’ya|Database Administ...|$63188.65| 58.366955| 45.541603|
|352|      Obie| Schoenrock|  Male|           Melaka|Database Administ...|$94743.26| 3.1121428|101.693504|
|452|    Rutger|     Kirman|  Male|          Zhosaly|Database Administ...|$74509.57| 45.485245|  64.08186|
|620|     Hamil| Eyckelbeck|  Male|           Gaoshi|Database Administ...|$10101.92| 29.184942| 105.05595|
|851|    Denney|    Godfrey|  Male|Villa del Rosario|Database Administ...|$52018.46|  7.683482|-72.490906|
|885|     Velma|Shackleford|Female|      Ambelókipoi|     Data Coordiator|$16676.56| 37.758293| 20.872854|
+---+----------+-----------+------+-----------------+--------------------+---------+----------+----------+

In [27]:
df1.filter(
    (df1.first_name.isin('Aldin','Valma'))
).show()

+---+----------+-------------+------+-----------+----------------+---------+----------+---------+
| id|first_name|    last_name|gender|       City|        JobTitle|   Salary|  Latitude|Longitude|
+---+----------+-------------+------+-----------+----------------+---------+----------+---------+
|569|     Valma|      Bratton|Female|  Kurayoshi|Web Developer II|$32665.89| 35.449905|133.76134|
|901|     Aldin|Matuszkiewicz|  Male|East London|        Operator|$41468.83|-32.954933|27.931913|
+---+----------+-------------+------+-----------+----------------+---------+----------+---------+

In [28]:
df1.select(
    df1.first_name,df1.first_name.substr(1,5).alias('name')
).show()

+----------+-----+
|first_name| name|
+----------+-----+
|   Melinde|Melin|
|  Kimberly|Kimbe|
|    Alvera|Alver|
|   Shannon|Shann|
|  Sherwood|Sherw|
|     Maris|Maris|
|     Masha|Masha|
|   Goddart|Godda|
|      Roth| Roth|
|      Bran| Bran|
|    Kylynn|Kylyn|
|       Rey|  Rey|
|      Kerr| Kerr|
|    Mickie|Micki|
|    Kaspar|Kaspa|
|    Norbie|Norbi|
|    Claude|Claud|
|     Thain|Thain|
|  Tiffanie|Tiffa|
|    Ettore|Ettor|
+----------+-----+
only showing top 20 rows

#**Applying Multible Filters**

In [29]:
df1.filter(
    (df1.first_name.isin('Aldin','Valma')) & (df1.City.like('%ondon'))
).show()

+---+----------+-------------+------+-----------+--------+---------+----------+---------+
| id|first_name|    last_name|gender|       City|JobTitle|   Salary|  Latitude|Longitude|
+---+----------+-------------+------+-----------+--------+---------+----------+---------+
|901|     Aldin|Matuszkiewicz|  Male|East London|Operator|$41468.83|-32.954933|27.931913|
+---+----------+-------------+------+-----------+--------+---------+----------+---------+

In [30]:
df1.filter(
    (df1.first_name.isin('Aldin','Valma')) | (df1.City.like('%ondon'))
).show()

+---+----------+-------------+------+-----------+----------------+---------+----------+---------+
| id|first_name|    last_name|gender|       City|        JobTitle|   Salary|  Latitude|Longitude|
+---+----------+-------------+------+-----------+----------------+---------+----------+---------+
|569|     Valma|      Bratton|Female|  Kurayoshi|Web Developer II|$32665.89| 35.449905|133.76134|
|901|     Aldin|Matuszkiewicz|  Male|East London|        Operator|$41468.83|-32.954933|27.931913|
+---+----------+-------------+------+-----------+----------------+---------+----------+---------+

#**Running SQL In DataFrame**

In [31]:
df1.registerTempTable("original")

In [33]:
query1 = spark.sql("select * from original")
query1.show()

+---+----------+----------+------+---------------+--------------------+---------+----------+----------+
| id|first_name| last_name|gender|           City|            JobTitle|   Salary|  Latitude| Longitude|
+---+----------+----------+------+---------------+--------------------+---------+----------+----------+
|  1|   Melinde| Shilburne|Female|      Nowa Ruda| Assistant Professor|$57438.18| 50.577408| 16.496717|
|  2|  Kimberly|Von Welden|Female|         Bulgan|       Programmer II|$62846.60|  48.82316| 103.52182|
|  3|    Alvera|  Di Boldi|Female|           null|                null|$57576.52| 39.994747|116.339775|
|  4|   Shannon| O'Griffin|  Male|  Divnomorskoye|Budget/Accounting...|$61489.23| 44.504723| 38.130016|
|  5|  Sherwood|   Macieja|  Male|      Mytishchi|            VP Sales|$63863.09|      null| 37.648994|
|  6|     Maris|      Folk|Female|Kinsealy-Drinan|      Civil Engineer|$30101.16| 53.426613|-6.1644998|
|  7|     Masha|    Divers|Female|         Dachun|                null|$25090.87| 24.879416|118.930115|
|  8|   Goddart|     Flear|  Male|      Trélissac|Desktop Support T...|$46116.36| 45.190517| 0.7423124|
|  9|      Roth|O'Cannavan|  Male|         Heitan|VP Product Manage...|$73697.10| 32.027935| 106.65711|
| 10|      Bran|   Trahear|  Male|       Arbeláez|Mechanical System...|$68098.42|  4.272793|-74.416016|
| 11|    Kylynn|   Lockart|Female|       El Cardo|Nuclear Power Eng...|$13604.63|     -5.85| -79.88333|
| 12|       Rey|    Meharg|Female|    Wangqingtuo|Systems Administr...|$73423.70|  39.17238| 116.93161|
| 13|      Kerr|    Braden|  Male|      Sułkowice|Compensation Analyst|$33432.99|  49.81518| 19.377174|
| 14|    Mickie| Whanstall|  Male|    Springfield|Assistant Media P...|$50838.53|  42.10148|-72.576675|
| 15|    Kaspar|     Pally|  Male|         Chrást|  Analyst Programmer|$40163.03|  49.79233| 13.491532|
| 16|    Norbie|    Gwyllt|  Male|         Xijiao|              Editor|$32492.73| 43.494576|  5.897802|
| 17|    Claude|    Briant|Female|      Mieścisko|Research Assistan...|$51862.48| 52.744167| 17.327864|
| 18|     Thain|    Habbon|  Male| Foros do Trapo|     Design Engineer|$42135.67| 38.696247| -8.709834|
| 19|  Tiffanie|  Pattison|Female|    Jabungsisir|Senior Financial ...|$91925.08|-7.7232566| 113.46868|
| 20|    Ettore|  Gerriets|  Male|          Pedra| Staff Accountant IV|$73921.33| 40.717205|-8.3625145|
+---+----------+----------+------+---------------+--------------------+---------+----------+----------+
only showing top 20 rows

In [36]:
query2 = spark.sql("select concat(first_name, '', last_name) as full_name from original")
query2.show()

+------------------+
|         full_name|
+------------------+
|  MelindeShilburne|
|KimberlyVon Welden|
|    AlveraDi Boldi|
|  ShannonO'Griffin|
|   SherwoodMacieja|
|         MarisFolk|
|       MashaDivers|
|      GoddartFlear|
|    RothO'Cannavan|
|       BranTrahear|
|     KylynnLockart|
|         ReyMeharg|
|        KerrBraden|
|   MickieWhanstall|
|       KasparPally|
|      NorbieGwyllt|
|      ClaudeBriant|
|       ThainHabbon|
|  TiffaniePattison|
|    EttoreGerriets|
+------------------+
only showing top 20 rows

#**Calculated Column**

In [40]:
df2 = df1.withColumn(
    "Clean_Salary",
    df1.Salary.substr(2,100).cast('float')
)
df2.show()

+---+----------+----------+------+---------------+--------------------+---------+----------+----------+------------+
| id|first_name| last_name|gender|           City|            JobTitle|   Salary|  Latitude| Longitude|Clean_Salary|
+---+----------+----------+------+---------------+--------------------+---------+----------+----------+------------+
|  1|   Melinde| Shilburne|Female|      Nowa Ruda| Assistant Professor|$57438.18| 50.577408| 16.496717|    57438.18|
|  2|  Kimberly|Von Welden|Female|         Bulgan|       Programmer II|$62846.60|  48.82316| 103.52182|     62846.6|
|  3|    Alvera|  Di Boldi|Female|           null|                null|$57576.52| 39.994747|116.339775|    57576.52|
|  4|   Shannon| O'Griffin|  Male|  Divnomorskoye|Budget/Accounting...|$61489.23| 44.504723| 38.130016|    61489.23|
|  5|  Sherwood|   Macieja|  Male|      Mytishchi|            VP Sales|$63863.09|      null| 37.648994|    63863.09|
|  6|     Maris|      Folk|Female|Kinsealy-Drinan|      Civil Engineer|$30101.16| 53.426613|-6.1644998|    30101.16|
|  7|     Masha|    Divers|Female|         Dachun|                null|$25090.87| 24.879416|118.930115|    25090.87|
|  8|   Goddart|     Flear|  Male|      Trélissac|Desktop Support T...|$46116.36| 45.190517| 0.7423124|    46116.36|
|  9|      Roth|O'Cannavan|  Male|         Heitan|VP Product Manage...|$73697.10| 32.027935| 106.65711|     73697.1|
| 10|      Bran|   Trahear|  Male|       Arbeláez|Mechanical System...|$68098.42|  4.272793|-74.416016|    68098.42|
| 11|    Kylynn|   Lockart|Female|       El Cardo|Nuclear Power Eng...|$13604.63|     -5.85| -79.88333|    13604.63|
| 12|       Rey|    Meharg|Female|    Wangqingtuo|Systems Administr...|$73423.70|  39.17238| 116.93161|     73423.7|
| 13|      Kerr|    Braden|  Male|      Sułkowice|Compensation Analyst|$33432.99|  49.81518| 19.377174|    33432.99|
| 14|    Mickie| Whanstall|  Male|    Springfield|Assistant Media P...|$50838.53|  42.10148|-72.576675|    50838.53|
| 15|    Kaspar|     Pally|  Male|         Chrást|  Analyst Programmer|$40163.03|  49.79233| 13.491532|    40163.03|
| 16|    Norbie|    Gwyllt|  Male|         Xijiao|              Editor|$32492.73| 43.494576|  5.897802|    32492.73|
| 17|    Claude|    Briant|Female|      Mieścisko|Research Assistan...|$51862.48| 52.744167| 17.327864|    51862.48|
| 18|     Thain|    Habbon|  Male| Foros do Trapo|     Design Engineer|$42135.67| 38.696247| -8.709834|    42135.67|
| 19|  Tiffanie|  Pattison|Female|    Jabungsisir|Senior Financial ...|$91925.08|-7.7232566| 113.46868|    91925.08|
| 20|    Ettore|  Gerriets|  Male|          Pedra| Staff Accountant IV|$73921.33| 40.717205|-8.3625145|    73921.33|
+---+----------+----------+------+---------------+--------------------+---------+----------+----------+------------+
only showing top 20 rows

In [43]:
df2.withColumn(
    'monthly_Salary',
    df2.Clean_Salary/12
).show()

+---+----------+----------+------+---------------+--------------------+---------+----------+----------+------------+------------------+
| id|first_name| last_name|gender|           City|            JobTitle|   Salary|  Latitude| Longitude|Clean_Salary|    monthly_Salary|
+---+----------+----------+------+---------------+--------------------+---------+----------+----------+------------+------------------+
|  1|   Melinde| Shilburne|Female|      Nowa Ruda| Assistant Professor|$57438.18| 50.577408| 16.496717|    57438.18| 4786.514973958333|
|  2|  Kimberly|Von Welden|Female|         Bulgan|       Programmer II|$62846.60|  48.82316| 103.52182|     62846.6|    5237.216796875|
|  3|    Alvera|  Di Boldi|Female|           null|                null|$57576.52| 39.994747|116.339775|    57576.52| 4798.043294270833|
|  4|   Shannon| O'Griffin|  Male|  Divnomorskoye|Budget/Accounting...|$61489.23| 44.504723| 38.130016|    61489.23|   5124.1025390625|
|  5|  Sherwood|   Macieja|  Male|      Mytishchi|            VP Sales|$63863.09|      null| 37.648994|    63863.09| 5321.924153645833|
|  6|     Maris|      Folk|Female|Kinsealy-Drinan|      Civil Engineer|$30101.16| 53.426613|-6.1644998|    30101.16|2508.4300130208335|
|  7|     Masha|    Divers|Female|         Dachun|                null|$25090.87| 24.879416|118.930115|    25090.87|  2090.90576171875|
|  8|   Goddart|     Flear|  Male|      Trélissac|Desktop Support T...|$46116.36| 45.190517| 0.7423124|    46116.36|3843.0299479166665|
|  9|      Roth|O'Cannavan|  Male|         Heitan|VP Product Manage...|$73697.10| 32.027935| 106.65711|     73697.1| 6141.425130208333|
| 10|      Bran|   Trahear|  Male|       Arbeláez|Mechanical System...|$68098.42|  4.272793|-74.416016|    68098.42| 5674.868489583333|
| 11|    Kylynn|   Lockart|Female|       El Cardo|Nuclear Power Eng...|$13604.63|     -5.85| -79.88333|    13604.63|1133.7191569010417|
| 12|       Rey|    Meharg|Female|    Wangqingtuo|Systems Administr...|$73423.70|  39.17238| 116.93161|     73423.7| 6118.641927083333|
| 13|      Kerr|    Braden|  Male|      Sułkowice|Compensation Analyst|$33432.99|  49.81518| 19.377174|    33432.99|2786.0823567708335|
| 14|    Mickie| Whanstall|  Male|    Springfield|Assistant Media P...|$50838.53|  42.10148|-72.576675|    50838.53| 4236.544270833333|
| 15|    Kaspar|     Pally|  Male|         Chrást|  Analyst Programmer|$40163.03|  49.79233| 13.491532|    40163.03|3346.9192708333335|
| 16|    Norbie|    Gwyllt|  Male|         Xijiao|              Editor|$32492.73| 43.494576|  5.897802|    32492.73|   2707.7275390625|
| 17|    Claude|    Briant|Female|      Mieścisko|Research Assistan...|$51862.48| 52.744167| 17.327864|    51862.48| 4321.873372395833|
| 18|     Thain|    Habbon|  Male| Foros do Trapo|     Design Engineer|$42135.67| 38.696247| -8.709834|    42135.67|3511.3059895833335|
| 19|  Tiffanie|  Pattison|Female|    Jabungsisir|Senior Financial ...|$91925.08|-7.7232566| 113.46868|    91925.08| 7660.423177083333|
| 20|    Ettore|  Gerriets|  Male|          Pedra| Staff Accountant IV|$73921.33| 40.717205|-8.3625145|    73921.33| 6160.110677083333|
+---+----------+----------+------+---------------+--------------------+---------+----------+----------+------------+------------------+
only showing top 20 rows

In [44]:
df1.withColumn(
    "are_they_female",
    when(df1.gender == "Female","Yes").otherwise("No")
).show()

+---+----------+----------+------+---------------+--------------------+---------+----------+----------+---------------+
| id|first_name| last_name|gender|           City|            JobTitle|   Salary|  Latitude| Longitude|are_they_female|
+---+----------+----------+------+---------------+--------------------+---------+----------+----------+---------------+
|  1|   Melinde| Shilburne|Female|      Nowa Ruda| Assistant Professor|$57438.18| 50.577408| 16.496717|            Yes|
|  2|  Kimberly|Von Welden|Female|         Bulgan|       Programmer II|$62846.60|  48.82316| 103.52182|            Yes|
|  3|    Alvera|  Di Boldi|Female|           null|                null|$57576.52| 39.994747|116.339775|            Yes|
|  4|   Shannon| O'Griffin|  Male|  Divnomorskoye|Budget/Accounting...|$61489.23| 44.504723| 38.130016|             No|
|  5|  Sherwood|   Macieja|  Male|      Mytishchi|            VP Sales|$63863.09|      null| 37.648994|             No|
|  6|     Maris|      Folk|Female|Kinsealy-Drinan|      Civil Engineer|$30101.16| 53.426613|-6.1644998|            Yes|
|  7|     Masha|    Divers|Female|         Dachun|                null|$25090.87| 24.879416|118.930115|            Yes|
|  8|   Goddart|     Flear|  Male|      Trélissac|Desktop Support T...|$46116.36| 45.190517| 0.7423124|             No|
|  9|      Roth|O'Cannavan|  Male|         Heitan|VP Product Manage...|$73697.10| 32.027935| 106.65711|             No|
| 10|      Bran|   Trahear|  Male|       Arbeláez|Mechanical System...|$68098.42|  4.272793|-74.416016|             No|
| 11|    Kylynn|   Lockart|Female|       El Cardo|Nuclear Power Eng...|$13604.63|     -5.85| -79.88333|            Yes|
| 12|       Rey|    Meharg|Female|    Wangqingtuo|Systems Administr...|$73423.70|  39.17238| 116.93161|            Yes|
| 13|      Kerr|    Braden|  Male|      Sułkowice|Compensation Analyst|$33432.99|  49.81518| 19.377174|             No|
| 14|    Mickie| Whanstall|  Male|    Springfield|Assistant Media P...|$50838.53|  42.10148|-72.576675|             No|
| 15|    Kaspar|     Pally|  Male|         Chrást|  Analyst Programmer|$40163.03|  49.79233| 13.491532|             No|
| 16|    Norbie|    Gwyllt|  Male|         Xijiao|              Editor|$32492.73| 43.494576|  5.897802|             No|
| 17|    Claude|    Briant|Female|      Mieścisko|Research Assistan...|$51862.48| 52.744167| 17.327864|            Yes|
| 18|     Thain|    Habbon|  Male| Foros do Trapo|     Design Engineer|$42135.67| 38.696247| -8.709834|             No|
| 19|  Tiffanie|  Pattison|Female|    Jabungsisir|Senior Financial ...|$91925.08|-7.7232566| 113.46868|            Yes|
| 20|    Ettore|  Gerriets|  Male|          Pedra| Staff Accountant IV|$73921.33| 40.717205|-8.3625145|             No|
+---+----------+----------+------+---------------+--------------------+---------+----------+----------+---------------+
only showing top 20 rows

#**Grouping By**